// Pure settlement logic — no Prisma, no I/O.
//
// This module is deliberately side-effect free so that the rules can be
// imported directly by the tests (tests/settlement-logic.test.ts) instead of
// being re-implemented as a copy. The previous bet-logic.test.ts duplicated
// checkSelectionWon by hand, which meant a real bug and its copy could agree
// on the bug and both would pass.
//
// Four outcomes are distinguished, because they mean very different things to
// a bettor:
//
//   WON        — the selection beat its line; contributes its real odds.
//   LOST       — the selection missed its line; kills the whole ticket.
//   VOID       — the event itself was cancelled/voided (Match.status ===
//                'VOID', or the match was POSTPONED/CANCELLED). Contributes a
//                multiplier of 1.00 and does NOT kill the ticket.
//   UNRESOLVED — there is not enough information to decide yet (the match has
//                no score yet, or a half-time market with no half-time data).
//                The ticket stays PENDING and is re-evaluated on the next run.
//
// UNRESOLVED is the crucial one: it must never collapse into LOST, or a match
// that finished before its result was recorded would silently wipe out a
// bettor's stake (see §9 of AUDIT_TEHNIC_BETV2.md, CRITICAL #2).

export type SelectionOutcome = 'WON' | 'LOST' | 'VOID' | 'UNRESOLVED';

export interface MatchState {
  status: string;
  homeScore: number | null;
  awayScore: number | null;
  halfTimeHome: number | null;
  halfTimeAway: number | null;
}

export interface BetSelectionInput {
  market: string;
  selection: string;
  odds: number;
  match: MatchState;
}

export interface EvaluatedSelection extends BetSelectionInput {
  outcome: SelectionOutcome;
}

export type TicketStatus = 'PENDING' | 'WON' | 'LOST';

export interface BetEvaluation {
  status: TicketStatus;
  selections: EvaluatedSelection[];
  /** Product of the winning legs' odds, with void legs contributing 1.00. */
  effectiveTotalOdds: number;
  /** round(stake * effectiveTotalOdds, 2) — the single payout figure. */
  effectivePotentialReturn: number;
  voidCount: number;
  winCount: number;
}

/** Round to 2 decimals, the precision every monetary column uses. */
const round2 = (n: number) => Math.round(n * 100) / 100;

// Match statuses that void the event itself. A match an admin has marked VOID
// belongs here alongside POSTPONED/CANCELLED: in all three cases the event did
// not produce a result, so the selection drops out of the accumulator at 1.00
// rather than settling it. This is distinct from Bet.status === 'CANCELLED',
// which is a bettor-initiated cancellation of the whole ticket.
export const VOID_MATCH_STATUSES = ['VOID', 'POSTPONED', 'CANCELLED'];

// Handicap selections are generated by odds_engine.py as `"Casa {line}"` /
// `"Fora {abs(line)}"`, e.g. market HANDICAP_n1_5 has legs "Casa -1.5" and
// "Fora 1.5". The line therefore lives in the *label*, and the two legs are
// mirror images: the away leg of a -1.5 handicap is the away side receiving
// +1.5, not applying -1.5. Parsing the label (instead of assuming a side from
// the market name) is what keeps the away formula from having its sign
// flipped — the bug recorded as CRITICAL #1 in the audit.
const HANDICAP_RE = /^(Casa|Fora)\s+(-?\d+(?:\.\d+)?)$/;

const parseHandicap = (
  selection: string
): { team: 'HOME' | 'AWAY'; line: number } | null => {
  const parsed = HANDICAP_RE.exec(selection.trim());
  if (!parsed) return null;
  return { team: parsed[1] === 'Casa' ? 'HOME' : 'AWAY', line: parseFloat(parsed[2]) };
};

// Over/under legs are exactly "Mais X.5" and "Menos X.5". Anything else is not
// a valid leg of this market and must not be silently treated as the opposite
// side, which is what the old `selection === 'Mais X.5' ? a : b` ternary did.
const overUnder = (selection: string, total: number, line: number): SelectionOutcome => {
  if (selection === `Mais ${line}`) return total > line ? 'WON' : 'LOST';
  if (selection === `Menos ${line}`) return total < line ? 'WON' : 'LOST';
  return 'VOID';
};

/**
 * Evaluates one selection against a finished match.
 *
 * Returns UNRESOLVED when the match has no usable result, so the caller can
 * leave the ticket PENDING instead of guessing.
 */
export const checkSelectionOutcome = (
  market: string,
  selection: string,
  match: { homeScore: number | null; awayScore: number | null; halfTimeHome: number | null; halfTimeAway: number | null }
): SelectionOutcome => {
  const { homeScore, awayScore } = match;

  // A finished match whose result was never recorded is not a loss for the
  // bettor. Returning UNRESOLVED keeps the ticket PENDING until an admin (or
  // the feed) supplies the score. This used to `return false`, which settled
  // the whole ticket as LOST and destroyed the stake.
  if (homeScore === null || homeScore === undefined) return 'UNRESOLVED';
  if (awayScore === null || awayScore === undefined) return 'UNRESOLVED';

  const home = homeScore;
  const away = awayScore;
  const total = home + away;
  const win = (condition: boolean): SelectionOutcome => (condition ? 'WON' : 'LOST');

  switch (market) {
    case '1X2':
      if (selection === '1') return win(home > away);
      if (selection === 'X') return win(home === away);
      if (selection === '2') return win(away > home);
      return 'VOID';

    case 'DUPLA_HIPOTESE':
      if (selection === '1X') return win(home >= away);
      if (selection === 'X2') return win(away >= home);
      if (selection === '12') return win(home !== away);
      return 'VOID';

    case 'MARCAS_0_5':
      return overUnder(selection, total, 0.5);
    case 'MARCAS_1_5':
      return overUnder(selection, total, 1.5);
    case 'MARCAS_2_5':
      return overUnder(selection, total, 2.5);
    case 'MARCAS_3_5':
      return overUnder(selection, total, 3.5);
    case 'MARCAS_4_5':
      return overUnder(selection, total, 4.5);

    case 'AMBAS_MARCAM':
      if (selection === 'Sim') return win(home > 0 && away > 0);
      if (selection === 'Não') return win(home === 0 || away === 0);
      return 'VOID';

    case 'RESULTADO_CORRETO':
      return win(selection === `${home}-${away}`);

    case 'RESULTADO_INTERVALO': {
      const { halfTimeHome, halfTimeAway } = match;
      // No feed populates half-time scores, so there is genuinely nothing to
      // settle against. That is UNRESOLVED, not VOID: the match was played
      // normally, we simply lack the data, and the bettor must not be
      // charged for our missing feed field.
      if (halfTimeHome === null || halfTimeHome === undefined) return 'UNRESOLVED';
      if (halfTimeAway === null || halfTimeAway === undefined) return 'UNRESOLVED';
      if (selection === '1') return win(halfTimeHome > halfTimeAway);
      if (selection === 'X') return win(halfTimeHome === halfTimeAway);
      if (selection === '2') return win(halfTimeAway > halfTimeHome);
      return 'VOID';
    }

    case 'IMPAR_PAR':
      if (selection === 'Ímpar') return win(total % 2 === 1);
      if (selection === 'Par') return win(total % 2 === 0);
      return 'VOID';

    case 'GOLOS_0':
    case 'GOLOS_1':
    case 'GOLOS_2':
    case 'GOLOS_3':
    case 'GOLOS_4':
    case 'GOLOS_5':
    case 'GOLOS_6': {
      const expected = parseInt(market.split('_').pop() || '0', 10);
      return win(total === expected);
    }
  }

  // Handicap markets share one implementation: the line comes from the leg
  // label, so HANDICAP_0_0 (draw-no-bet) falls out correctly — the adjusted
  // scores are equal on a draw, which is a push, and a push is a VOID leg
  // (multiplier 1.00), not a loss.
  if (market.startsWith('HANDICAP')) {
    const leg = parseHandicap(selection);
    if (!leg) return 'VOID';

    const adjusted = leg.team === 'HOME' ? home + leg.line : away + leg.line;
    const opponent = leg.team === 'HOME' ? away : home;

    if (adjusted > opponent) return 'WON';
    if (adjusted < opponent) return 'LOST';
    return 'VOID'; // push, only reachable when line === 0
  }

  // An unrecognised market/selection cannot be settled, so it must not be
  // charged to the bettor. VOID keeps the ticket alive at 1.00 instead of
  // silently deciding it lost.
  return 'VOID';
};

/**
 * Decides the fate of a whole ticket and computes the single payout figure.
 *
 * Rules (in order):
 *   1. Any LOST selection        -> ticket LOST, payout 0, no refund. Checked
 *                                   before UNRESOLVED on purpose: one lost leg
 *                                   already kills the accumulator, so the
 *                                   ticket must not sit PENDING (and therefore
 *                                   cancellable) waiting for the other matches.
 *   2. Any UNRESOLVED selection  -> ticket stays PENDING, nothing is settled.
 *   3. Otherwise                 -> ticket WON. Void legs multiply by 1.00.
 *
 * A ticket whose legs are all VOID is reported as WON with an effective total
 * odds of 1.00, so the payout is exactly the stake. It is deliberately NOT
 * LOST (the bettor did not lose) and NOT CANCELLED (CANCELLED is reserved for
 * a bettor-initiated cancellation and implies a refund path of its own).
 */
export const evaluateBet = (selections: BetSelectionInput[], stake: number): BetEvaluation => {
  const evaluated: EvaluatedSelection[] = selections.map((s) => {
    // An event that was voided, postponed or cancelled has no result to
    // settle against, whatever the score columns happen to contain.
    if (VOID_MATCH_STATUSES.includes(s.match.status)) return { ...s, outcome: 'VOID' as const };
    // Anything not FINISHED (SCHEDULED, LIVE, or an unknown status) is not
    // ready to be judged. It must not fall through to the score-based check,
    // which would read a partial 0-0 as a real result.
    if (s.match.status !== 'FINISHED') return { ...s, outcome: 'UNRESOLVED' as const };
    return { ...s, outcome: checkSelectionOutcome(s.market, s.selection, s.match) };
  });

  const voidCount = evaluated.filter((s) => s.outcome === 'VOID').length;
  const winCount = evaluated.filter((s) => s.outcome === 'WON').length;

  // LOST is checked FIRST, deliberately. An accumulator dies on its first
  // losing leg: the remaining legs can never make the ticket win, whatever
  // they do. Testing UNRESOLVED first left such a ticket PENDING until every
  // other match finished, which kept it refundable via cancel() the whole
  // time — the exact hole that let a bettor cancel a ticket that had already
  // lost. Settling the loss as soon as it is known closes that window.
  if (evaluated.some((s) => s.outcome === 'LOST')) {
    return { status: 'LOST', selections: evaluated, effectiveTotalOdds: 0, effectivePotentialReturn: 0, voidCount, winCount };
  }

  if (evaluated.some((s) => s.outcome === 'UNRESOLVED')) {
    return { status: 'PENDING', selections: evaluated, effectiveTotalOdds: 0, effectivePotentialReturn: 0, voidCount, winCount };
  }

  // Every surviving leg is WON or VOID. Void legs contribute exactly 1.00, so
  // a single void leg demotes a parlay to a single instead of killing it.
  // The product is rounded to the same 2-decimal precision placeBet stores, and
  // the payout is derived from that rounded figure — so the ticket satisfies
  // stake * totalOdds === potentialReturn, which the placement path did not.
  const effectiveTotalOdds = round2(
    evaluated.reduce((acc, s) => acc * (s.outcome === 'VOID' ? 1 : s.odds), 1)
  );
  const effectivePotentialReturn = round2(stake * effectiveTotalOdds);

  return { status: 'WON', selections: evaluated, effectiveTotalOdds, effectivePotentialReturn, voidCount, winCount };
};

/** Human-readable summary of a ticket's void legs, for notifications. */
export const describeVoids = (voidCount: number): string =>
  voidCount === 0
    ? ''
    : ` (${voidCount} ${voidCount === 1 ? 'seleção anulada' : 'seleções anuladas'})`;
